### ISSUE TITLE
AniList to TvDB or TheXem DB support

### ISSUE THREAD

**Issue by Andy2244** [vosmiic/jellyfin-ani-sync#15]
Any plans to add support to map tvdb to Anilist/AniDB, this way we can keep the tvdb meta's + season view and let the scrobbler handle the mappings?

Examples on how others do this:
`custom_mappings.yaml`
https://github.com/RickDB/PlexAniSync
and user maintained list
https://github.com/mizz141/PlexAniSync-Mappings

If you adapt the yaml 1:1 we could use the same maintained lists for both plugins?

More complex is use those translation lists or https://thexem.info api
https://github.com/Anime-Lists/anime-lists

**Comment by vosmiic** [comment]
We use a different method to identify anime in this plugin, where we query the provider database using the name in Jellyfin (which is set by whichever metadata provider you use). 
While this leads to the anime detection being slightly unreliable, it requires no manual work from the user or other parties.
The advantage to using a dedicated list is obviously the detection being basically 100% accurate but requires manual entry by users. 
That being said I could quite easily integrate a list of anime mappings to AniList (like the ones linked) into the plugin, and fall back to querying the API database if the show is not present in the list.
I will ask if the owner of the repo is willing to share the list (I don't feel right just using it without permission), but I entirely understand if they are not willing to give us access.
I don't think that maintaining our own list of mappings to the separate providers (AniList, MAL and Kitsu) will be very achievable at the moment considering how many users we have. Of course that may change later on. 
I will keep this open and let you know of the progress.

**Comment by Andy2244** [comment]
The main issue is that the name of TvDB is not always the same as Anilist, which uses AniDB  + synonyms. Also AniDB/Anilist is not season aware. That's where the list-mappings comes in and can map different TVDB seasons to the separate Anilist entries.

Example:
```
  - title: "Attack on Titan"
    synonyms:
      - "Shingeki no Kyojin"
    seasons:
      - season: 1
        anilist-id: 16498
      - season: 2
        anilist-id: 20958
      - season: 3
        anilist-id: 99147
      - season: 3
        anilist-id: 104578
        start: 13
      - season: 4
        anilist-id: 110277
      - season: 4
        anilist-id: 131681
        start: 17
```
In this example we also have "sub" seasons, that start at different absolute numbering in TVDB.
